// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZHszu3oLjbbfZoUyaiCGVCfaAKNQRmbA',
    appId: '1:902299834871:web:47982171d18e8b63a476f2',
    messagingSenderId: '902299834871',
    projectId: 'trackerflutter-aca46',
    authDomain: 'trackerflutter-aca46.firebaseapp.com',
    storageBucket: 'trackerflutter-aca46.firebasestorage.app',
    measurementId: 'G-WTQH98LGPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARtXbwtVnmiETlk930LqX7fjCcmXyDG8k',
    appId: '1:902299834871:android:751c88c712f2efc3a476f2',
    messagingSenderId: '902299834871',
    projectId: 'trackerflutter-aca46',
    storageBucket: 'trackerflutter-aca46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaru7z9TsscOtoIFu7Dp6CGr2LhjwJs2o',
    appId: '1:902299834871:ios:2f0556e2b0b5f046a476f2',
    messagingSenderId: '902299834871',
    projectId: 'trackerflutter-aca46',
    storageBucket: 'trackerflutter-aca46.firebasestorage.app',
    iosBundleId: 'com.example.fuelTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaru7z9TsscOtoIFu7Dp6CGr2LhjwJs2o',
    appId: '1:902299834871:ios:2f0556e2b0b5f046a476f2',
    messagingSenderId: '902299834871',
    projectId: 'trackerflutter-aca46',
    storageBucket: 'trackerflutter-aca46.firebasestorage.app',
    iosBundleId: 'com.example.fuelTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZHszu3oLjbbfZoUyaiCGVCfaAKNQRmbA',
    appId: '1:902299834871:web:68815083fabf94b6a476f2',
    messagingSenderId: '902299834871',
    projectId: 'trackerflutter-aca46',
    authDomain: 'trackerflutter-aca46.firebaseapp.com',
    storageBucket: 'trackerflutter-aca46.firebasestorage.app',
    measurementId: 'G-0SMT9ZJ0LW',
  );
}
